### ISSUE TITLE
Useless IF Statement

### ISSUE THREAD

**Issue by PoisnFang** [GoranHalvarsson/SitecoreBlazor#63]
In TheRouter.cs file the if statement is never false, because you rewrite the context. Additionally in the App.razor file under Project.BlazorSite it will never render "Not Found"
`        <NotFound>
            <p>Sorry, there's nothing at this address.</p>
        </NotFound>
`
Line 105 TheRouter.cs
`                     // Custom - Not valid route
            if (context.Handler == null || !LanguageService.HasValidLanguageInUrl(locationPath))
                context = SetErrorContext(locationPath);
            **// THIS WILL NEVER BE FALSE BECAUSE OF THE CODE ABOVE**
            if (context.Handler != null)         
`

**Comment by GoranHalvarsson** [comment]
Thank you for finding this, will fix at once :-)
